BlogProject.Mvc/Areas/Admin/Models/UserViewModel.cs
using BlogProject.Entities.Concrete;

namespace BlogProject.Mvc.Areas.Admin.Models
{
    public class UserViewModel
    {
        public User User { get; set; }
    }
}

BlogProject.Mvc/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BlogProject.Entities.Concrete;
using BlogProject.Entities.Dtos;
using BlogProject.Mvc.Areas.Admin.Models;
using BlogProject.Mvc.Helpers.Abstract;
using BlogProject.Services.Abstract;
using BlogProject.Shared.Utilities.Extensions;
using BlogProject.Shared.Utilities.Results.ComplexType;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace BlogProject.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin,Editor")]
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;
         
        
        public CategoryController(ICategoryService categoryService,UserManager<User> userManager, IMapper mapper,IImageHelper imageHelper):base(userManager,mapper,imageHelper)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAllByNonDeletedAsync();
            return View(result.Data);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_CategoryAddPartial");
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryAddDto categoryAddDto)
        {
           
            if (ModelState.IsValid)
            {
                var result = await _categoryService.AddAsync(categoryAddDto, LoggedInUser.UserName);
                if (result.ResultStatus==ResultStatus.Success)
                {
                    var categoryAddAjaxModel=JsonSerializer.Serialize(new CategoryAddAjaxViewModel
                    {
                        CategoryDto=result.Data,
                        CategoryAddPartial=await this.RenderViewToStringAsync("_CategoryAddPartial",categoryAddDto)
                    });
                    return Json(categoryAddAjaxModel);
                }
            }
            var categoryAddAjaxErrorModel = JsonSerializer.Serialize(new CategoryAddAjaxViewModel
            {
              
                CategoryAddPartial = await this.RenderViewToStringAsync("_CategoryAddPartial", categoryAddDto)
            });
            return Json(categoryAddAjaxErrorModel);
        }

        public async Task<JsonResult> GetAllCategories()
        {
            var result = await _categoryService.GetAllByNonDeletedAsync();
            var categories = JsonSerializer.Serialize(result.Data, new JsonSerializerOptions
            {
                ReferenceHandler =ReferenceHandler.Preserve
            });
            return Json(categories);

        }
    

        [HttpGet]
        public async Task<IActionResult> Update(int categoryId)
        {

            var result = await _categoryService.GetCategoryUpdateDtoAsync(categoryId);
            if (result.ResultStatus==ResultStatus.Success)
            {
                return PartialView("_CategoryUpdatePartial", result.Data);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Update(CategoryUpdateDto categoryUpdateDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _categoryService.UpdateAsync(categoryUpdateDto, LoggedInUser.UserName);
                if (result.ResultStatus == ResultStatus.Success)
                {
                    var categoryUpdateAjaxModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
                    {
                        CategoryDto = result.Data,
                        CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
                    });
                    return Json(categoryUpdateAjaxModel);
                }
            }
            var categoryUpdateAjaxErrorModel = JsonSerializer.Serialize(new CategoryUpdateAjaxViewModel
            {
                CategoryUpdatePartial = await this.RenderViewToStringAsync("_CategoryUpdatePartial", categoryUpdateDto)
            });
            return Json(categoryUpdateAjaxErrorModel);

        }

        public async Task<JsonResult> Delete(int categoryId)
        {
            var result = await _categoryService.DeleteAsync(categoryId, LoggedInUser.UserName);
            var deletedCategory= JsonSerializer.Serialize(result.Data);
            return Json(deletedCategory);
        }

    }
}

BlogProject.Mvc/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Hosting;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BlogProject.Entities.Concrete;
using BlogProject.Entities.Dtos;
using BlogProject.Mvc.Areas.Admin.Models;
using BlogProject.Services.Extension;
using BlogProject.Shared.Utilities.Extensions;
using BlogProject.Shared.Utilities.Results.ComplexType;
using System;
using System.IO;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using BlogProject.Entities.ComplexTypes;
using BlogProject.Mvc.Helpers.Abstract;
using NToastNotify;

namespace BlogProject.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IImageHelper _ımageHelper;
        private readonly IToastNotification _toastNotification;


        private readonly IMapper _mapper;
        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, IMapper mapper, IImageHelper ımageHelper, IToastNotification toastNotification)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mapper = mapper;
            _ımageHelper = ımageHelper;
            _toastNotification = toastNotification;
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
         
            return View(new UserListDto
            {
                Users = users,
                ResultStatus = ResultStatus.Success
            });
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {

            return View("UserLogin");
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDto userLoginDto)
        {
            if (ModelState.IsValid)
            {

                var user = await _userManager.FindByEmailAsync(userLoginDto.Email);

                if (user != null)
                {
                    var result = await _signInManager.PasswordSignInAsync(user, userLoginDto.Password, userLoginDto.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Eposta Adresiniz veya Şifreniz Yanlış");
                        return View("UserLogin");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Eposta Adresiniz veya Şifreniz Yanlış");
                    return View("UserLogin");
                }
            }
            else
            {
                return View("UserLogin");
            }

        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home", new { Area = "" });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAllUsers()
        {
            var users = await _userManager.Users.ToListAsync();
            var userListDto = JsonSerializer.Serialize(new UserListDto
            {
                Users = users,
                ResultStatus = ResultStatus.Success
            }, new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve
            });
            return Json(userListDto);
        }
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            return PartialView("_UserAddPartial");
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add(UserAddDto userAddDto)
        {
            if (ModelState.IsValid)
            {
                var uploadedImageDtoResult = await _ımageHelper.Upload(userAddDto.UserName, userAddDto.PictureFile,PictureType.User);
                userAddDto.Picture = uploadedImageDtoResult.ResultStatus == ResultStatus.Success ? uploadedImageDtoResult.Data.FullName : "userImages/defaultUser.png";
                var user = _mapper.Map<User>(userAddDto);
                var result = await _userManager.CreateAsync(user, userAddDto.Password);
                if (result.Succeeded)
                {
                    var userAddAjaxModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            ResultStatus = ResultStatus.Success,
                            Message = $"{user.UserName} adlı kullanıcı başarıyla eklenmiştir",
                            User = user
                        },
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjaxModel);
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    var userAddAjaxErrorModel = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserAddDto = userAddDto,
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjaxErrorModel);
                }
            }
            var userAddAjaxErrorModelState = JsonSerializer.Serialize(new UserAddAjaxViewModel
            {
                UserAddDto = userAddDto,
                UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
            });
            return Json(userAddAjaxErrorModelState);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> Delete(int userId)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                var deletedUser = JsonSerializer.Serialize(new UserDto
                {
                    ResultStatus = ResultStatus.Success,
                    Message = $"{user.UserName} adlı kullanıcı başarıyla silinmiştir.",
                    User = user
                });
                return Json(deletedUser);
            }
            else
            {
                string errorMessages = string.Empty;
                foreach (var error in result.Errors)
                {
                    errorMessages = $"{error.Description}";
                }
                var deletedUserErrorModel = JsonSerializer.Serialize(new UserDto
                {
                    ResultStatus = ResultStatus.Error,
                    Message = $"{user.UserName} adl kullanıcı silinirken bir hata oluştu \n{errorMessages}",
                    User = user
                });
                return Json(deletedUserErrorModel);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<PartialViewResult> Update(int userId)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == userId);
            var userUpdateDto = _mapper.Map<UserUpdateDto>(user);
            return PartialView("_UserUpdatePartial", userUpdateDto);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(UserUpdateDto userUpdateDto)
        {
            if (ModelState.IsValid)
            {
                bool isNewPictureUploaded = default;
                var oldUser = await _userManager.FindByIdAsync(userUpdateDto.Id.ToString());
                var oldUserPicture = oldUser.Picture;
                if (userUpdateDto.PictureFile != null)
                {
                    var uploadedImageDtoResult = await _ımageHelper.Upload(userUpdateDto.UserName, userUpdateDto.PictureFile, PictureType.User);
                    userUpdateDto.Picture = uploadedImageDtoResult.ResultStatus == ResultStatus.Success ? uploadedImageDtoResult.Data.FullName : "userImages/defaultUser.png";
                    if (oldUserPicture != "userImages/defaultUser.png")
                    {
                        isNewPictureUploaded = true;
                    }
                }
                var updatedUser = _mapper.Map<UserUpdateDto, User>(userUpdateDto, oldUser);
                var result = await _userManager.UpdateAsync(updatedUser);
                if (result.Succeeded)
                {
                    if (isNewPictureUploaded)
                    {
                        _ımageHelper.Delete(oldUserPicture);
                    }
                    var userUpdateViewModel = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            ResultStatus = ResultStatus.Success,
                            Message = $"{updatedUser.UserName} adlı kullanıcı başarıyla güncellenmiştir",
                            User = updatedUser
                        },
                        UserUpdatePartial = await this.RenderViewToStringAsync("_UserUpdatePartial", userUpdateDto)

                    });
                    return Json(userUpdateViewModel);
                }
                else
                {

BlogProject.Mvc/Areas/Admin/Views/User/AccessDenied.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>401 Error - Erişim Reddedildi.</title>
    <link href="~/AdminArea/css/styles.css" rel="stylesheet" />
    <link href="~/AdminArea/css/httpErrorBgAnimation.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="bg"></div>
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4 text-white">
                                <h1 class="display-1">403</h1>
                                <p class="lead">Erişiminiz Reddedilmiştir./ Access Denied</p>
                                <p>Access to this resource is denied.</p>
                                <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                                    <i class="fas fa-arrow-left mr-1"></i>
                                    Return to Dashboard
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Programmers Blog 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminArea/js/scripts.js"></script>
</body>
</html>

BlogProject.Mvc/Areas/Admin/Views/User/ChangeDetails.cshtml
@model BlogProject.Entities.Dtos.UserUpdateDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Profil Duzenle";
}
<div class="row">
    <div class="col-lg-6 offset-lg-3">
        <div class="card-header">
            <h1 class="text-center"><span class="fas-fa-edit"></span>Profil Duzenle</h1>
        </div>
  
        <div class="card-body">
            <div class="modal-body">
                <form asp-controller="User" asp-action="ChangeDetails" id="form-user-update" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="UserName"></label>
                        <input class="form-control" asp-for="UserName" placeholder="Lütfen Kullanıcı Adı Giriniz" />
                        <span class="text-danger" asp-validation-for="UserName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input type="email" class="form-control" asp-for="Email" placeholder="Lütfen Eposta Giriniz" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="Lütfen Telefon Numarası Giriniz" />
                        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Picture"></label>
                        <input type="hidden" asp-for="Picture" />
                        <img class="my-image" src="~/img/@Model.Picture" alt="@Model.UserName" />
                    </div>
                    <div class="form-group">
                        <label asp-for="PictureFile"></label>
                        <input type="file" accept="image/*" asp-for="PictureFile" class="form-control-file" />
                        <span class="text-danger" asp-validation-for="PictureFile"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"><span class="fas fa-save"></span> Kaydet</button>
                        <a class="btn btn-danger btn-block" asp-area="Admin"asp-controller="Home"asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                    </div>

                </form>
            </div>


        </div>
    </div>
</div>

BlogProject.Mvc/Areas/Admin/Views/User/Index.cshtml
@using BlogProject.Shared.Utilities.Results.ComplexType
@model BlogProject.Entities.Dtos.UserListDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Kullanıcılar Index";
}
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a></li>
    <li class="breadcrumb-item active" asp-area="Admin" asp-controller="Category" asp-action="Index"><a asp-area="Admin" asp-controller="User" asp-action="Index">Kullanıcılar</a></li>
</ol>
@if (Model.ResultStatus == ResultStatus.Success)
{
    <div id="modalPlaceHolder" aria-hidden="true"></div>
    <div class="card mb-4 mt-2">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Kullanıcılar
        </div>
        <div class="card-body">
            <div class="spinner-border" role="status" style="display: none;">
                <span class="sr-only">Yükleniyor...</span>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="usersTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Kullanıcı Adı</th>
                            <th>E-Posta Adresi</th>
                            <th>Telefon Numarası</th>
                            <th>Resim</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Kullanıcı Adı</th>
                            <th>E-Posta Adresi</th>
                            <th>Telefon Numarası</th>
                            <th>Resim</th>
                            <th>İşlemler</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var user in Model.Users)
                        {
                            <tr name="@user.Id">
                                <td>@user.Id</td>
                                <td>@user.UserName</td>
                                <td>@user.Email</td>
                                <td>@user.PhoneNumber</td>
                                <td>
                                    <img src="~/img/@user.Picture" class="my-image-table" alt="@user.Picture" />
                                </td>
                                <td>
                                    <button class="btn btn-primary btn-sm btn-update" data-id="@user.Id"><span class="fas fa-edit"></span></button>
                                    <button class="btn btn-danger btn-sm btn-delete" data-id="@user.Id"><span class="fas fa-minus-circle"></span></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
@if (Model.ResultStatus == ResultStatus.Error)
{
    <div class="alert alert-danger mt-3">
        @Model.Message <br />
        Dashboard sayfasına geri dönmek için lütfen <a class="alert-link" asp-area="Admin" asp-controller="Home" asp-action="Index">tıklayınız.</a>
    </div>
}
@section Scripts
    {
    <script src="~/AdminArea/js/userIndex.js" type="application/ecmascript"></script>
}

    <img src="https://readme-typing-svg.demolab.com?font=Consolos&size=18&duration=2000&pause=100&multiline=true&width=500&height=80&lines=Alpaslan+Akgun;.Net Developer+%7C+Computer Science+%7C+;+%7C+Senior Software Trainer+%7C+Computer+Vision+%7C+" alt="Typing SVG" />

BlogProject.Mvc/Areas/Admin/Views/User/PasswordChange.cshtml
@model BlogProject.Entities.Dtos.UserPasswordChangeDto
@{
    Layout = "_Layout";
    ViewBag.Title = "Şifre Değiştir";
}
<div class="row mt-2">
    <div class="col-lg-6 offset-lg-3">
        <div class="card-header">
            <h1 class="text-center"><span class="fas-fa-key"></span>Şifre Değiştir</h1>
        </div>

        <div class="card-body">
            <div class="modal-body">
                <form asp-controller="User" asp-action="PasswordChange" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary"></div>

                    <div class="form-group">
                        <label asp-for="CurrentPassword"></label>
                        <input type="password" class="form-control" asp-for="CurrentPassword" placeholder="Lütfen mevcut şifrenizi giriniz" />
                        <span class="text-danger" asp-validation-for="CurrentPassword"></span>
                    </div>
                     <div class="form-group">
                        <label asp-for="NewPassword"></label>
                        <input type="password" class="form-control" asp-for="NewPassword" placeholder="Lütfen mevcut şifrenizi giriniz" />
                        <span class="text-danger" asp-validation-for="NewPassword"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RepeatPassword"></label>
                        <input type="password" class="form-control" asp-for="RepeatPassword" placeholder="Lütfen mevcut şifrenizi giriniz" />
                        <span class="text-danger" asp-validation-for="RepeatPassword"></span>
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"><span class="fas fa-save"></span> Kaydet</button>
                        <a class="btn btn-danger btn-block" asp-area="Admin" asp-controller="Home" asp-action="Index"><span class="fas fa-times"></span> İptal</a>
                    </div>

                </form>
            </div>


        </div>
    </div>
</div>

BlogProject.Mvc/Areas/Admin/Views/User/UserLogin.cshtml
@model BlogProject.Entities.Dtos.UserLoginDto
@{
    ViewBag.Title="Giriş Yap";
    Layout="_UserLoginLayout";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4"><span class="fas fa-house-user"></span> Giriş Yap</h3></div>
                <div class="card-body">
                    <form asp-controller="User" asp-action="Login" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label class="small mb-1" asp-for="Email">Email</label>
                            <input class="form-control py-4" asp-for="Email" type="email" placeholder="Lütfen emailinizi giriniz."/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="small mb-1" asp-for="Password">Password</label>
                            <input class="form-control py-4" asp-for="Password" type="password" placeholder="Lütfen şifrenizi giriniz."/>
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-checkbox">
                                <input class="custom-control-input" asp-for="RememberMe" type="checkbox"/>
                                <label class="custom-control-label" asp-for="RememberMe"></label>
                            </div>
                        </div>
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                            <a class="btn btn-secondary text-white"><span class="fas fa-user-lock "></span> Şifremi Unuttum</a>
                            <button class="btn btn-primary" type="submit"><span class="fas fa-sign-in-alt"></span> Giriş Yap</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                 <a class="btn btn-success btn-block text-white"><span class="fas fa-user-edit"></span> Kayıt Ol</a>
                </div>
            </div>
        </div>
    </div>
</div>

BlogProject.Mvc/Areas/Admin/Views/User/_UserAddPartial.cshtml
@model BlogProject.Entities.Dtos.UserAddDto


<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> <span class="fas fa-plus">  </span>Kullanıcı Ekle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="İptal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Add" id="form-user-add">
                    <input name="IsValid"type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div asp-validation-summary="All" class="text-danger" id="validation-summary" aria-hidden="true" style="display:none;"></div>
                    <div class="form-group">
                        <label asp-for="UserName"></label>
                        <input class="form-control" asp-for="UserName" placeholder="Lütfen Kullanıcı Adı Giriniz"/>
                        <span class="text-danger" asp-validation-for="UserName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input type="email" class="form-control" asp-for="Email" placeholder="Lütfen Eposta Giriniz" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password"></label>
                        <input type="password" class="form-control" asp-for="Password" placeholder="Lütfen Şifre Giriniz" />
                        <span class="text-danger" asp-validation-for="Password"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="Lütfen Telefon Numarası Giriniz" />
                        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PictureFile"></label>
                        <input type="file" accept="image/*" form-control" asp-for="PictureFile" class="form-control-file" />
                        <span class="text-danger" asp-validation-for="PictureFile"></span>
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-block" data-dismiss="modal"><span class="fas fa-time"></span>İptal</button>
                <button type="button" class="btn btn-primary btn-block" id="btnSave"><span class="fas fa-save"></span>Ekle</button>
            </div>
        </div>
    </div>
</div>